name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      run: |
        EXTRA_FILES="LICENSE README.md"
        GOOS=linux GOARCH=amd64
        echo build ${GOOS}-${GOARCH} ...
        GOOS=${GOOS} GOARCH=${GOARCH} go build -v -o release-${GOOS}-${GOARCH} .
        zip -r release-${GOOS}-${GOARCH}.zip release-${GOOS}-${GOARCH} ${EXTRA_FILES}
        rm release-${GOOS}-${GOARCH}

        GOOS=linux GOARCH=arm64
        echo build ${GOOS}-${GOARCH} ...
        GOOS=${GOOS} GOARCH=${GOARCH} go build -v -o release-${GOOS}-${GOARCH} .
        zip -r release-${GOOS}-${GOARCH}.zip release-${GOOS}-${GOARCH} ${EXTRA_FILES}
        rm release-${GOOS}-${GOARCH}

        GOOS=darwin GOARCH=amd64
        echo build ${GOOS}-${GOARCH} ...
        GOOS=${GOOS} GOARCH=${GOARCH} go build -v -o release-${GOOS}-${GOARCH} .
        zip -r release-${GOOS}-${GOARCH}.zip release-${GOOS}-${GOARCH} ${EXTRA_FILES}
        rm release-${GOOS}-${GOARCH}

        GOOS=darwin GOARCH=arm64
        echo build ${GOOS}-${GOARCH} ...
        GOOS=${GOOS} GOARCH=${GOARCH} go build -v -o release-${GOOS}-${GOARCH} .
        zip -r release-${GOOS}-${GOARCH}.zip release-${GOOS}-${GOARCH} ${EXTRA_FILES}
        rm release-${GOOS}-${GOARCH}

        GOOS=windows GOARCH=amd64
        echo build ${GOOS}-${GOARCH} ...
        GOOS=${GOOS} GOARCH=${GOARCH} go build -v -o release-${GOOS}-${GOARCH}.exe .
        zip -r release-${GOOS}-${GOARCH}.zip release-${GOOS}-${GOARCH}.exe ${EXTRA_FILES}
        rm release-${GOOS}-${GOARCH}.exe
        ls -al

    - name: Test
      run: go test -v ./...

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release-*.zip
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}