name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
        #排除windows arm64
        exclude:
          - os: windows
            arch: arm64

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Set up Cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download Modules
      run: go mod download

    - name: Test
      #测试只运行一次
      if: matrix.os == 'linux' && matrix.arch == 'amd64'
      run: |
          go vet ./...
          go test -v ./...

    - name: Build for ${{ matrix.os }}(${{ matrix.arch }})
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: |
        appVersion=1.0.0
        appBuildDate=$(TZ=Asia/Shanghai date +%F)
        appGitCommitHash=${GITHUB_SHA}
        appModuleName=github.com/${GITHUB_REPOSITORY}
        buildLdFlags="-X ${appModuleName}/cmd.appBuildDate=${appBuildDate}"
        buildLdFlags="${buildLdFlags} -X ${appModuleName}/cmd.appGitCommitHash=${appGitCommitHash}"

        EXTRA_FILES="LICENSE README.md"
        SAVE_FILE_NAME="release-${GOOS}-${GOARCH}"
        if [[ "${GOOS}" == "windows" ]]; then SAVE_FILE_NAME="${SAVE_FILE_NAME}.exe" ; fi
        go build -v -ldflags "${buildLdFlags}" -o ${SAVE_FILE_NAME} .
        zip -r release-${GOOS}-${GOARCH}.zip ${SAVE_FILE_NAME} ${EXTRA_FILES}
        rm ${SAVE_FILE_NAME}
        ls -al

    - name: Release for ${{ matrix.os }}(${{ matrix.arch }})
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release-*.zip
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}